global:
  scrape_interval:     5s
  evaluation_interval: 5s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'customexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['customexporter:8000']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    scrape_interval: 5s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']


#remote_write:
#  - url: "http://35.242.227.62:9201/write"
      #- url: "http://host.docker.internal:9202/write"
      #    queue_config:
      #      capacity: 2100
      #      max_samples_per_send: 700
    #min_shards: 500
    #tls_config:
    #    cert_file: "/etc/prometheus/my_key.pem"
    #    key_file: "/etc/prometheus/my_key.key"
    #    insecure_skip_verify: true



alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - 'alertmanager:9093'